// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Undefine.Repository.Models;

namespace Undefine.Web.Migrations
{
    [DbContext(typeof(UndefineDBContext))]
    partial class UndefineDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-preview1-28290")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Undefine.Domain.Model.Sys_Module", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnName("CreationTime");

                    b.Property<string>("CreationUserId")
                        .IsRequired()
                        .HasColumnName("CreationUserId")
                        .HasMaxLength(100);

                    b.Property<string>("CreationUserName")
                        .IsRequired()
                        .HasColumnName("CreationUserName")
                        .HasMaxLength(30);

                    b.Property<int>("Enabled")
                        .HasColumnName("Enabled");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnName("Icon")
                        .HasMaxLength(50);

                    b.Property<bool>("IsAutoExpand")
                        .HasColumnName("IsAutoExpand");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("ModifyTime");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnName("ModifyUserId")
                        .HasMaxLength(100);

                    b.Property<string>("ModifyUserName")
                        .IsRequired()
                        .HasColumnName("ModifyUserName")
                        .HasMaxLength(30);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasMaxLength(30);

                    b.Property<string>("ParentId")
                        .IsRequired()
                        .HasColumnName("ParentId")
                        .HasMaxLength(100);

                    b.Property<string>("ParentName")
                        .IsRequired()
                        .HasColumnName("ParentName")
                        .HasMaxLength(30);

                    b.Property<int>("Sort")
                        .HasColumnName("Sort");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnName("Url")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Sys_Module");
                });

            modelBuilder.Entity("Undefine.Domain.Model.Sys_ModuleElement", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasMaxLength(100);

                    b.Property<string>("BgColor")
                        .IsRequired()
                        .HasColumnName("BgColor")
                        .HasMaxLength(50);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnName("CreationTime");

                    b.Property<string>("CreationUserId")
                        .IsRequired()
                        .HasColumnName("CreationUserId")
                        .HasMaxLength(100);

                    b.Property<string>("CreationUserName")
                        .IsRequired()
                        .HasColumnName("CreationUserName")
                        .HasMaxLength(30);

                    b.Property<string>("DomId")
                        .IsRequired()
                        .HasColumnName("DomId")
                        .HasMaxLength(30);

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnName("Icon")
                        .HasMaxLength(50);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("ModifyTime");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnName("ModifyUserId")
                        .HasMaxLength(100);

                    b.Property<string>("ModifyUserName")
                        .IsRequired()
                        .HasColumnName("ModifyUserName")
                        .HasMaxLength(30);

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasColumnName("ModuleId")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasMaxLength(30);

                    b.Property<string>("Remark")
                        .HasColumnName("Remark")
                        .HasMaxLength(255);

                    b.Property<int>("Sort")
                        .HasColumnName("Sort");

                    b.HasKey("Id");

                    b.ToTable("Sys_ModuleElement");
                });

            modelBuilder.Entity("Undefine.Domain.Model.Sys_Relevance", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasMaxLength(100);

                    b.Property<string>("FirstId")
                        .IsRequired()
                        .HasColumnName("FirstId")
                        .HasMaxLength(100);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnName("Key")
                        .HasMaxLength(30);

                    b.Property<string>("SecondId")
                        .IsRequired()
                        .HasColumnName("SecondId")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Sys_Relevance");
                });

            modelBuilder.Entity("Undefine.Domain.Model.Sys_Role", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasMaxLength(100);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnName("CreationTime");

                    b.Property<string>("CreationUserId")
                        .IsRequired()
                        .HasColumnName("CreationUserId")
                        .HasMaxLength(100);

                    b.Property<string>("CreationUserName")
                        .IsRequired()
                        .HasColumnName("CreationUserName")
                        .HasMaxLength(30);

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("ModifyTime");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnName("ModifyUserId")
                        .HasMaxLength(100);

                    b.Property<string>("ModifyUserName")
                        .IsRequired()
                        .HasColumnName("ModifyUserName")
                        .HasMaxLength(30);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("Name")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Sys_Role");
                });

            modelBuilder.Entity("Undefine.Domain.Model.Sys_User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasMaxLength(100);

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnName("Account")
                        .HasMaxLength(30);

                    b.Property<DateTime>("CreationTime")
                        .HasColumnName("CreationTime");

                    b.Property<string>("CreationUserId")
                        .IsRequired()
                        .HasColumnName("CreationUserId")
                        .HasMaxLength(100);

                    b.Property<string>("CreationUserName")
                        .IsRequired()
                        .HasColumnName("CreationUserName")
                        .HasMaxLength(30);

                    b.Property<string>("LastLoginIp")
                        .IsRequired()
                        .HasColumnName("LastLoginIp")
                        .HasMaxLength(30);

                    b.Property<DateTime>("LastLoginTime")
                        .HasColumnName("LastLoginTime");

                    b.Property<DateTime?>("ModifyTime")
                        .HasColumnName("ModifyTime");

                    b.Property<string>("ModifyUserId")
                        .IsRequired()
                        .HasColumnName("ModifyUserId")
                        .HasMaxLength(100);

                    b.Property<string>("ModifyUserName")
                        .IsRequired()
                        .HasColumnName("ModifyUserName")
                        .HasMaxLength(30);

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnName("PassWord")
                        .HasMaxLength(255);

                    b.Property<int>("Sex")
                        .HasColumnName("Sex");

                    b.Property<int>("Status")
                        .HasColumnName("Status");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnName("UserName")
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.ToTable("Sys_User");
                });
#pragma warning restore 612, 618
        }
    }
}
